### ISSUE TITLE
can't connect to ssh.tmate.io

### ISSUE THREAD

**Issue by alouanemed** [tmate-io/tmate#107]
At first it asked me to generate a ssh key, which I did using ssh-keygen cmd
Ubuntu 16.04
tmate 2.2.1

```
$ tmate show-messages
Mon Apr 17 22:21:59 2017 [tmate] Connecting to ssh.tmate.io...

```

here is the [Logs from tmate](https://gist.github.com/alouanemed/2f9ce88a979c44aa5772abfd19da2a9c)

**Comment by kotp** [comment]
I am seeing the same problems on a machine using Linux Subsystem on Windows 10.  It works fine on my local machine, another person having just installed tmate.io and can only get that same message.

**Comment by kf6nux** [comment]
Workaround Verified on MacOS High Sierra: Remove any IPv6 addresses from your list of DNS resolvers.

**Comment by kf6nux** [comment]
@nviennot Based on your interest in issue #32 , I thought you might find the above workaround helpful for debugging purposes.

**Comment by hirishh** [comment]
on Ubuntu 16.04 I had to fallback to 1.8.10 (version provided with official ubuntu repos) to make it work. Version 2.2.1 is not showing the Token even if debug logs saying ssh auth with the server is ok.

**Comment by jezen** [comment]
I had this problem just now, and I solved it by removing any lines containing `tmate` from my `~/.ssh/known_hosts`.

**Comment by 4n3w** [comment]
Confirmed @kf6nux's fix above regarding removing any ipv6 DNS resolvers fixed this issue! 🍻

**Comment by pabloab** [comment]
Why is this issue closed? IT seems unclear the root of the issue. On an Ubuntu 18.04 with no IPv6 DNS resolver (at least not on `systemd-resolve --status`). Using v 2.2.1, the one  on default repo. Not sure if any PPA or .deb with newer versions is available.

**Comment by kf6nux** [comment]
@pabloab , does your issue match this one?  Can you provide more details?  Maybe `cat /etc/resolv.conf` and share your logs?

FWIW, I am unable to reproduce any issue with tmate 2.2.1 in an Ubuntu 18.04 OCI container.

**Comment by pabloab** [comment]
My `/etc/resolv.conf` looks:

    nameserver 127.0.0.53
    options edns0
    search <organizationDomain> <something>.<organizationDomain>

But AFAIK on systemd `systemd-resolve --status` is the source of trueth and I don't have any IPv6 on DNS Servers section.

I'm not sure why `nmcli device show | grep IP6.ADDRESS` return one IPv6 since there is none on Settings>Network>Wired>IPv6 (set to default, _Automatic_).

I think probably the issue comes from the firewall of my organization: I can ping ssh.tmate.io but `nc` return _No route to host_. Is possible to setup tmate to use other ports that might be available on that domain? For example 443, maybe using a protocol multiplexer like [sslh](https://github.com/yrutschle/sslh).

**Comment by heyakyra** [comment]
Anyone still landing here from google, the service is shut down permanently and it's time to switch: https://github.com/tmate-io/tmate/issues/322#issuecomment-5802770885
