### ISSUE TITLE
Session keeps open when you just close the terminal

### ISSUE THREAD

**Issue by capynet** [tmate-io/tmate#131]
Use case:
- I share my console
- My colleague connects to my console
- I close my console without "exit", just close the terminal window.
If you follow those steps will notice the other side connected person will still able to use the remote console.

This is a very dangerous behavior. When a host closes the terminal, the process should die.

**Comment by codylane** [comment]
I personally do see the danger in this use case.  

You invoke `tmate` which makes a connection to `tmate.io` (a server in the cloud), you accept that this is a shared resource and lives in the cloud and there maybe other clients with different namespaces all sharing this same host.  I don't know if that is what happens, but I assume that is what happens since this is a free service and you don't have to pay for it but based off what I know about ssh and tunneling I wouldn't be surprised that this is any different from the way `ssh-agent` works.

If you close your connection or close your terminal window and a client is still connected, they are connected to the `tmate.io` instance that still would remain open.  The *host* that you refer to is `tmate.io` in which you initiated your session throught so when you close your session and there is a client connected how the heck would `tmate` know that you are the `host` because you are not the host, `tmate.io` is and you are proxying your information through that host.  

I also could be mis-understanding something about your concern or how this works.  Here's a snippet from the technical details section of the documentation which is why I'm making a pretty good guess that it works as I described above.

![screen shot 2018-06-20 at 2 55 54 pm](https://user-images.githubusercontent.com/1258262/41684212-0f9f0936-749a-11e8-807c-3030ffefaf14.png)

**Comment by eddiewebb** [comment]
> If you close your connection or close your terminal window and a client is still connected, they are connected to the tmate.io instance that still would remain open.

I think the concern is that closing the terminal *doesn't* close the session/process, it detaches from it. The tmate server & tunnel are still running locally, and clients connected to the remote server can still interact with the local server through that running tmate tunnel.

If that happens to you have to re-attach to the session, and invoke `exit` for tmate to close the tunnel.

**Comment by kuien** [comment]
It makes sense to keep the session ALIVE when you detaches. It is not an issue.

**Comment by nviennot** [comment]
The fact that tmate keeps running in the background when you close your terminal window is indeed a desired feature (like tmux). But I concede that it is a bit surprising as tmate does not document this behavior.
