### ISSUE TITLE
How to run tmate on an already existing tmux session

### ISSUE THREAD

**Issue by Integralist** [tmate-io/tmate#26]
How can I run tmate on an already existing tmux session? Haven't been able to figure this out yet

**Comment by sukima** [comment]
I to find this solution better, Mainly because tmux is at version 1.9 and when I run tmate I loose many features in the tmux binary that tmate doesn't have.

**Comment by juandazapata** [comment]
Ping

**Comment by nviennot** [comment]
I don't see how to share an existing tmux session properly :/

**Comment by jaspervanbrian** [comment]
Hello, I just implemented a solution but it is **quite different**. I set up my `~/.bashrc`/`~/.zshrc` to open `tmux` initially. Here is my initial setup:

`
        # Launch TMUX
	# If not running interactively, do not do anything
	[[ $- != *i* ]] && return
	[[ -z "$TMUX" ]] && exec tmux
	tmux_count=$(tmux list-panes | wc -l)
	if [[ $tmux_count == 1 ]] ; then
	#	neofetch
		((tmux_count++))
	fi
`
Now I installed `tmate`, but I also wanted to execute `tmate` inside a `tmux` pane. Here's what I did:
`
# Check if user has opened tmate
if [[ -z "$ZSH_TMATE" ]]
then
	# Launch TMUX
	# If not running interactively, do not do anything
	[[ $- != *i* ]] && return
	[[ -z "$TMUX" ]] && exec tmux
	tmux_count=$(tmux list-panes | wc -l)
	if [[ $tmux_count == 1 ]] ; then
	#	neofetch
		((tmux_count++))
	fi

	# Alias tmate
	export ZSH_TMATE=tmate
	alias tmate="gnome-terminal"
else
	unset TMUX
	unset ZSH_TMATE
	exec tmate
fi
`
First, it checks if a `ZSH_TMATE` variable has been set. If no variable is detected, I will set the variable and will alias the `tmate` command to open a new `gnome-terminal` instance. 

It will open a new `gnome-terminal`, and on the `gnome-terminal` instance, it will check if a `ZSH_TMATE` variable is set. It will pass on the `else` case because you have set it earlier.

**Comment by sukima** [comment]
The solution is simple, nest TMUX inside TMate. Unfortunately the information above on how to do this seem rather complicated. Here is my take to add to the confusion and maybe it will help someone.

First understand your TMUX prefix key. By default this is <kbd>CTRL-B</kbd> In the following examples I have choosen to use <kbd>CTRL-Space</kbd> by use of this command in my `.tmux.conf` file:

```
set-option -g prefix C-Space
```

Next in your `.tmate.conf` file you have to change this. I choose <kbd>CTRL-y</kbd> in these examples. First unbind the prefix you set in `.tmux.conf` and redefine the prefix in `.tmate.conf` To make things even better I've taken the extra step of unbinding keys that I want to pass directly through to TMUX and turning the status off (as nesting would normally produce two status bars). Here is my full `.tmate.conf` file:

```
unbind-key C-Space
set-option -g prefix C-y
bind-key C-y send-prefix
unbind -n C-h
unbind -n C-j
unbind -n C-k
unbind -n C-l
set-option -g status off
```

Lastly, when I launch I do so in two steps. Since I live in TMUX normally I typically will detach and reattach inside tmate when I need. Alternatively I could also launch a new session inside tmate if I wish. The trick is when inside tmate to always prefix my TMUX commands with `TMUX=`. Here is an example:

```console
$ tmate
------------------- Inside tmate ---------------------
$ TMUX= tmux attach
```

**Comment by nviennot** [comment]
This should be easy to do once tmate decouples itself from tmux (a regular tmux attach inside a tmate session will be sufficient). Thank you @sukima for providing guidance.
