### ISSUE TITLE
Implement "Rogue Mode"

### ISSUE THREAD

**Issue by bsiegel** [tmate-io/tmate#35]
Wemux (https://github.com/zolrath/wemux) supports "rogue mode" which "allows the client to pair or work independently in another window (separate cursors) in the same tmux session."

This can be done with bare tmux by starting a tmux session in a terminal with a specific socket (`tmux -S /tmp/tmux-sock new`) and then creating another session using the same socket (`tmux -S /tmp/tmux-sock new`) in another terminal. Any chance that tmate could support this?

**Comment by nightscape** [comment]
:+1:

**Comment by pdbradley** [comment]
:+1:

**Comment by nviennot** [comment]
On wemux, the "rogue" mode is implemented by creating different sessions on the same tmux server.
With tmate, I don't think it makes much sense to share different sessions on the same server, because each session must have a different access token (otherwise sharing one session with someone means sharing all sessions with that same someone).
Also, I think the rogue mode should support having separate cursors within the same window.
For example one client could have his cursor in one pane, and another client in a different pane.
If both clients have the cursor in the same pane, it would behave as if rogue mode wasn't on.
It would be also useful to be able to turn that feature on and off during a session (e.g. "set rogue on" in the tmux command line). Maybe having it by default set to on would be a good idea. This might also be good direction for having a pane that can act somewhat like a chat window.
